# Generated by Django 4.2.2 on 2024-08-07 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('C', 'C'), ('D', 'D')], max_length=1)),
                ('computa_sac', models.BooleanField(default=False)),
                ('computa_ObraSocial', models.BooleanField(default=False)),
                ('computa_Aporte', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8)),
                ('cuil', models.CharField(max_length=13)),
                ('tipo_liquidacion', models.CharField(choices=[('M', 'M'), ('D', 'D'), ('H', 'H')], max_length=2)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('conyugue', models.BooleanField(default=False)),
                ('hijos', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('sicoss_cod_situacion', models.CharField(max_length=3)),
                ('sicoss_cod_condicion', models.CharField(max_length=3)),
                ('sicoss_cod_actividad', models.CharField(max_length=3)),
                ('sicoss_cod_mod_contratacion', models.CharField(max_length=3)),
                ('sicoss_cod_siniestrado', models.CharField(max_length=3)),
                ('sicoss_cod_localidad', models.CharField(max_length=3)),
                ('cod_obra_social', models.CharField(max_length=20)),
                ('cantidad_adherentes', models.IntegerField(default=0)),
                ('cbu', models.CharField(blank=True, max_length=22, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empleador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abierta', models.BooleanField(default=True)),
                ('periodo', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sueldos.empleado')),
                ('liquidacion', models.ForeignKey(limit_choices_to={'abierta': True}, on_delete=django.db.models.deletion.CASCADE, to='sueldos.liquidacion')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRecibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sueldos.concepto')),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sueldos.recibo')),
            ],
        ),
    ]
