# Generated by Django 4.2.2 on 2024-08-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sueldos', '0002_alter_liquidacion_options_liquidacion_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='empleador',
            new_name='empresa',
        ),
    ]
